

amg-coarse-solver.o: amg-coarse-solver.c ../include/amg-coarse-solver.h ../include/amg-type-def.h ../include/config.h ../include/mat.h ../include/op-blas.h ../include/utils.h ../include/vec.h internal.h

amg-cycle.o: amg-cycle.c ../include/amg-coarse-solver.h ../include/amg-cycle.h ../include/amg-setup.h ../include/amg-type-def.h ../include/amg-utils.h ../include/config.h ../include/mat.h ../include/op-blas.h ../include/op-coarsen.h ../include/op-inter.h ../include/op-smoother.h ../include/utils.h ../include/vec.h internal.h

amg-setup.o: amg-setup.c ../include/amg-coarse-solver.h ../include/amg-setup.h ../include/amg-type-def.h ../include/amg-utils.h ../include/config.h ../include/mat.h ../include/op-blas.h ../include/op-coarsen.h ../include/op-inter.h ../include/op-smoother.h ../include/utils.h ../include/vec.h internal.h

amg-utils.o: amg-utils.c ../include/amg-coarse-solver.h ../include/amg-type-def.h ../include/amg-utils.h ../include/config.h ../include/mat.h ../include/op-blas.h ../include/op-smoother.h ../include/utils.h ../include/vec.h internal.h

mat.o: mat.c ../include/amg-type-def.h ../include/config.h ../include/mat.h ../include/utils.h ../include/vec.h internal.h

op-blas.o: op-blas.c ../include/amg-type-def.h ../include/config.h ../include/mat.h ../include/op-blas.h ../include/utils.h ../include/vec.h internal.h

op-coarsen.o: op-coarsen.c ../include/amg-type-def.h ../include/config.h ../include/mat.h ../include/op-blas.h ../include/op-coarsen.h ../include/utils.h ../include/vec.h internal.h

op-inter.o: op-inter.c ../include/amg-type-def.h ../include/config.h ../include/mat.h ../include/op-blas.h ../include/op-inter.h ../include/utils.h ../include/vec.h internal.h

op-smoother.o: op-smoother.c ../include/amg-type-def.h ../include/config.h ../include/mat.h ../include/op-blas.h ../include/op-smoother.h ../include/utils.h ../include/vec.h internal.h

sxamg.o: sxamg.c ../include/amg-coarse-solver.h ../include/amg-cycle.h ../include/amg-setup.h ../include/amg-type-def.h ../include/amg-utils.h ../include/config.h ../include/mat.h ../include/op-blas.h ../include/op-coarsen.h ../include/op-inter.h ../include/op-smoother.h ../include/sxamg.h ../include/utils.h ../include/vec.h internal.h

utils.o: utils.c ../include/amg-type-def.h ../include/config.h ../include/utils.h internal.h

vec.o: vec.c ../include/amg-type-def.h ../include/config.h ../include/utils.h ../include/vec.h internal.h
